version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: fulkoping_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fulkoping_bibliotek
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
